#!/usr/bin/env python3
"""Fail if repository text includes unwanted authorship/tooling markers."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKERS = [
    "codex",
    "generated by",
    "ai-generated",
    "created with",
    "co-authored",
]
SKIP_DIRS = {".git", ".venv", "__pycache__", ".pytest_cache", ".ruff_cache", "automate_everything.egg-info"}
SKIP_FILES = {Path("scripts/check_no_markers.py")}


def should_skip(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    return rel in SKIP_FILES or any(part in SKIP_DIRS for part in rel.parts)


def main() -> int:
    hits = []
    for path in ROOT.rglob("*"):
        if should_skip(path) or not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        lower = text.lower()
        for marker in MARKERS:
            if marker in lower:
                hits.append(f"{path.relative_to(ROOT)}: contains '{marker}'")

    if hits:
        print("\n".join(hits))
        return 1

    print("Marker scan: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
